name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
      version:
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      IMAGE_VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18.13.0'
      - name: Set Version
        if: ${{ inputs.version != null }}
        run: npm version "${IMAGE_VERSION:-$GITHUB_SHA}" --allow-same-version
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        if: ${{ inputs.version != null }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
