name: Deploy Main Branch
on:
  push:
    branches: [ main ]

jobs:
  asd:
    name: Asd
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.ASD }}
      - run: echo ${{ secrets.NODE_AUTH_TOKEN }}
  build:
    uses: "./.github/workflows/build.yaml"
  deploy:
    needs:
      - build
    name: Deploy
    uses: "./.github/workflows/deploy.yaml"
