name: Deploy Main Branch
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  packages: none

jobs:
  build:
    uses: "./.github/workflows/build.yaml"
  deploy:
    needs:
      - build
    name: Deploy
    uses: "./.github/workflows/deploy.yaml"
    with:
      environment: test
