name: Deploy Main Branch
on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    uses: "./.github/workflows/build.yaml"
  deploy:
    needs:
      - build
    name: Deploy
    uses: "./.github/workflows/deploy.yaml"
    with:
      environment: test
